version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: mavarra-api
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_DB=${MONGODB_DB:-mavarra}
    ports:
      - "3001:3001"

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    image: mavarra-web
    ports:
      - "8080:80"
    depends_on:
      - api
